spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      acks: all
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:chatdb
